import path from 'path';
import fs from 'fs-extra';
import { InstalledSkill } from '../types';

const OPEN_SKILLS_START = '<!-- OPEN_SKILLS_START -->';
const OPEN_SKILLS_END = '<!-- OPEN_SKILLS_END -->';
const HOW_TO_USE_SECTION = '## How to Use Skills';

export interface UpdateAgentsMdOptions {
	cwd?: string;
	skills: InstalledSkill[];
}

export function getAgentsMdPath(cwd: string = process.cwd()): string {
	return path.join(cwd, 'AGENTS.md');
}

export function generateSkillsXml(skills: InstalledSkill[]): string {
	let skillsXml = `${OPEN_SKILLS_START}\n`;
	skillsXml += '<!-- This section is auto-generated by khmetskills -->\n\n';
	skillsXml += '<available_skills>\n';

	for (const skill of skills) {
		skillsXml += '  <skill>\n';
		skillsXml += `    <name>${escapeXml(skill.metadata.name)}</name>\n`;
		skillsXml += `    <description>${escapeXml(skill.metadata.description)}</description>\n`;
		skillsXml += `    <location>${escapeXml(skill.installedPath)}</location>\n`;
		skillsXml += `    <repository>${escapeXml(skill.repository)}</repository>\n`;
		skillsXml += `    <version>${escapeXml(skill.metadata.version)}</version>\n`;

		if (skill.metadata.tags && skill.metadata.tags.length > 0) {
			skillsXml += `    <tags>${escapeXml(skill.metadata.tags.join(', '))}</tags>\n`;
		}

		skillsXml += '  </skill>\n';
	}

	skillsXml += '</available_skills>\n';
	skillsXml += `${OPEN_SKILLS_END}\n`;

	return skillsXml;
}

export function createDefaultAgentsMd(skillsXml: string): string {
	let content = '# AGENTS.md\n\n';
	content += 'This file provides instructions and available skills for AI coding agents.\n\n';
	content += skillsXml;
	content = ensureHowToUseSkills(content);

	return content;
}

export function upsertSkillsSection(existingContent: string, skillsXml: string): string {
	if (!existingContent.includes(OPEN_SKILLS_START)) {
		const withSkills = `${existingContent.trimEnd()}\n\n${skillsXml}`;
		return ensureHowToUseSkills(withSkills);
	}

	const startIndex = existingContent.indexOf(OPEN_SKILLS_START);
	const endMarkerIndex = existingContent.indexOf(OPEN_SKILLS_END, startIndex);

	if (endMarkerIndex === -1) {
		const withSkills = `${existingContent.trimEnd()}\n\n${skillsXml}`;
		return ensureHowToUseSkills(withSkills);
	}

	const endIndex = endMarkerIndex + OPEN_SKILLS_END.length;
	const updated = `${existingContent.slice(0, startIndex)}${skillsXml}${existingContent.slice(endIndex)}`;

	return ensureHowToUseSkills(updated);
}

export function ensureHowToUseSkills(content: string): string {
	if (content.includes(HOW_TO_USE_SECTION)) {
		return content;
	}

	let updated = content.trimEnd();
	updated += '\n\n## How to Use Skills\n\n';
	updated += 'To load a specific skill, use the following command:\n\n';
	updated += '```bash\n';
	updated += 'khmetskills read <skill-name>\n';
	updated += '```\n\n';
	updated += 'For example:\n';
	updated += '```bash\n';
	updated += 'khmetskills read code-review\n';
	updated += '```\n';

	return updated;
}

export async function updateAgentsMd(options: UpdateAgentsMdOptions): Promise<string> {
	const cwd = options.cwd ?? process.cwd();
	const agentsMdPath = getAgentsMdPath(cwd);
	const skillsXml = generateSkillsXml(options.skills);

	if (!(await fs.pathExists(agentsMdPath))) {
		const initialContent = createDefaultAgentsMd(skillsXml);
		await fs.writeFile(agentsMdPath, initialContent, 'utf-8');
		return agentsMdPath;
	}

	const existingContent = await fs.readFile(agentsMdPath, 'utf-8');
	const updatedContent = upsertSkillsSection(existingContent, skillsXml);
	await fs.writeFile(agentsMdPath, updatedContent, 'utf-8');

	return agentsMdPath;
}

function escapeXml(value: string): string {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&apos;');
}
